# This workflow will trigger the build and deployment of the project on a docker kubernetes node

name: "Docker-Kubernetes Build and Deploy"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic-docker:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic-docker:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up K8s context
      run: |
        kubectl config set-cluster docker-desktop --server=https://kubernetes.docker.internal:6443
        kubectl config set-context docker-desktop --cluster=docker-desktop --user=docker-desktop
        kubectl config use-context docker-desktop

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/petclinic-deployment.yaml
        kubectl set image deployment/spring-petclinic-docker spring-petclinic-docker=${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic-docker:${{ github.sha }}
  
  
