name: Example workflow for S3 Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - uses: actions/checkout@v1

        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: '11'

        - name: Build with Maven
          run: mvn clean install

        - name: Deploy to S3
          run: |
            aws s3 cp target/spring-petclinic-2.7.0-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET }}/spring-petclinic-2.7.0-SNAPSHOT.jar
  
        - name: Invalidate CloudFront Cache
          run: |
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
